version: "3.2"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    expose:
      - "32181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=32181

  backend:
    image: openjdk
    command: /bin/bash /var/log/pack/bin/watchZK
    ports:
      - "80:80"
    environment:
      - ZK_HOST=zookeeper
      - ZK_PORT=32181
      - ZK_TIMEOUT=2 seconds
      - BIND_PORT=80
      - INTERFACE=backend
    depends_on:
      - zookeeper
    links:
      - zookeeper
    volumes:
      - ../target/pack:/var/log/pack
