version: "3.2"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    expose:
      - "32181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=32181

  backend:
    image: openjdk
    command: /bin/bash /var/data/pack/bin/watchZK
    expose:
      - "9000"
    environment:
      - ZK_HOST=zookeeper
      - ZK_PORT=32181
      - ZK_TIMEOUT=2 seconds
    depends_on:
      - zookeeper
    links:
      - zookeeper
    volumes:
      - type: bind
        source: ../target/pack
        target: /var/data/pack

  frontend:
    image: nginx
    volumes:
      - ../target/web:/data/www:ro
      - ../nginx/frontend-nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend
    links:
      - backend