version: "3.2"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    expose:
      - "32181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=32181

  backend:
    image: openjdk
    command: /bin/bash /var/data/pack/bin/watchZK
    ports:
      - "8080:8080"
    environment:
      - ZK_HOST=zookeeper
      - ZK_PORT=32181
      - ZK_TIMEOUT=2 seconds
      - BIND_PORT=8080
    depends_on:
      - zookeeper
    links:
      - zookeeper
    volumes:
      - type: bind
        source: ../target/pack
        target: /var/data/pack
