version: "3.2"

services:
  frontend:
    image: nginx
    volumes:
      - ../src/main/resources:/data:ro
      - ../nginx/frontend-nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend
    links:
      - backend